# Site settings
title: Konstantinos Kouropalatis
email: kouropalatis02@gmail.com
description: >-
  Awesome Description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kouropalatis.github.io" # the base hostname & protocol for your site
github_username: kouropalatis

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache

# Navigation links for top-right menu
header_pages:
  - index.md
  - about.md
  - bokeh.md